[package]
name = "laya-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "laya"
path = "src/main.rs"

[dependencies]
laya-core.workspace = true
laya-rank.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
blake3.workspace = true
