#!/bin/sh
# Regenerate the Homebrew formula (packaging/homebrew/laya-codex.rb) for a published release:
# version, URLs and sha256 values come from the release's <asset>.sha256 files.
#
#   scripts/update-formula.sh 0.2.0                    # or v0.2.0
#   scripts/update-formula.sh 0.2.0 path/to/laya-codex.rb
#
# Releases from v0.2.0 on ship laya-codex-v<ver>-<target>.tar.gz (the CLI `laya-codex`, env vars
# LAYA_CODEX_*) and moon-v<ver>-<target>.tar.gz. The formula is written only after every checksum
# was fetched and validated, so a failed run leaves it untouched. LAYA_CODEX_RELEASES_URL points
# at a mirror (or a file:// tree in tests).
set -eu

REPO="pilotspace/laya-codex"
RELEASES_URL="${LAYA_CODEX_RELEASES_URL:-https://github.com/$REPO/releases}"
MAC=aarch64-apple-darwin
LINUX=x86_64-unknown-linux-gnu

die() { printf 'update-formula: error: %s\n' "$*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $0 <version> [formula]"
ver="${1#v}"
case "$ver" in
    [0-9]*.[0-9]*.[0-9]*) ;;
    *) die "version must look like 1.2.3 (got '$1')" ;;
esac
formula="${2:-$(cd "$(dirname "$0")/.." && pwd)/packaging/homebrew/laya-codex.rb}"
tag="v$ver"
base="$RELEASES_URL/download/$tag"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

# get_sum <asset>: its sha256 from <asset>.sha256; fails if missing or malformed.
get_sum() {
    curl --fail --silent --location --retry 3 --connect-timeout 15 --max-time 60 \
        --output "$tmp/one" "$base/$1.sha256" 2>/dev/null || return 1
    s="$(cut -d' ' -f1 <"$tmp/one")"
    printf '%s' "$s" | grep -Eq '^[0-9a-f]{64}$' || die "bad checksum in $1.sha256: '$s'"
    printf '%s' "$s"
}

for a in "laya-codex-$tag-$MAC" "moon-$tag-$MAC" "laya-codex-$tag-$LINUX" "moon-$tag-$LINUX"; do
    s="$(get_sum "$a.tar.gz")" || die "cannot fetch $a.tar.gz.sha256 (is $tag published? v0.2.0 is the first release named laya-codex)"
    printf 'update-formula: %s.tar.gz %s\n' "$a" "$s"
    eval "sum_$(printf '%s' "$a" | tr -c 'a-zA-Z0-9\n' _)=\$s"
done
key() { printf 'sum_%s' "$(printf '%s' "$1" | tr -c 'a-zA-Z0-9\n' _)"; }
val() { eval "printf '%s' \"\$$(key "$1")\""; }

cat >"$tmp/formula.rb" <<EOF
# Homebrew formula for laya-codex. Published as Formula/laya-codex.rb in pilotspace/homebrew-tap:
#   brew install pilotspace/tap/laya-codex
# Generated by scripts/update-formula.sh $ver; regenerate rather than edit by hand.
class LayaCodex < Formula
  desc "Ranked code retrieval for Claude Code (tree-sitter + Moon + Laya re-ranker)"
  homepage "https://github.com/pilotspace/laya-codex"
  # laya-codex is Apache-2.0; the bundled Moon sidecar ships with a GPL-3.0 LICENSE text.
  license all_of: ["Apache-2.0", "GPL-3.0-only"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "$base/laya-codex-$tag-$MAC.tar.gz"
      sha256 "$(val "laya-codex-$tag-$MAC")"

      resource "moon" do
        url "$base/moon-$tag-$MAC.tar.gz"
        sha256 "$(val "moon-$tag-$MAC")"
      end
    end
  end

  on_linux do
    on_intel do
      url "$base/laya-codex-$tag-$LINUX.tar.gz"
      sha256 "$(val "laya-codex-$tag-$LINUX")"

      resource "moon" do
        url "$base/moon-$tag-$LINUX.tar.gz"
        sha256 "$(val "moon-$tag-$LINUX")"
      end
    end
  end

  def install
    # laya-codex resolves its own symlink and runs the Moon in ../libexec, so the binary is linked
    # into bin as usual and \`init\` writes the bare \`laya-codex\` command (not a versioned Cellar
    # path). Moon stays in libexec: homebrew-core's unrelated \`moon\` (moonrepo) owns bin/moon.
    bin.install "laya-codex"
    pkgshare.install "THIRD-PARTY-LICENSES.txt"
    resource("moon").stage do
      libexec.install "moon"
      (pkgshare/"moon").install "LICENSE", "SOURCE"
    end
  end

  def caveats
    <<~EOS
      The laya-code re-ranker (~850 MB, a fine-tune of the Laya model) is not part of this
      formula. Without it laya-codex ranks lexically. To download and verify it:
        curl -fsSL https://raw.githubusercontent.com/pilotspace/laya-codex/main/install.sh | sh -s -- --model-only

      Enable it in Claude Code, either everywhere with the plugin (inside Claude Code):
        /plugin marketplace add pilotspace/laya-codex
        /plugin install laya-codex@laya-codex
      or per repository:
        laya-codex init --repo /path/to/repo
      Then check the setup with:
        laya-codex doctor --repo /path/to/repo

      Upgrading from 0.1.x: the CLI is now \`laya-codex\` (was \`laya\`) and its environment
      variables are LAYA_CODEX_* (were LAYA_*). Re-run \`laya-codex init\` in repositories set up
      with \`laya init\` and delete their old \`laya hook\` entries.
    EOS
  end

  test do
    require "json"

    assert_match "Usage: laya-codex", shell_output("#{bin}/laya-codex --help")
    assert_match "Usage: moon", shell_output("#{libexec}/moon --help")

    # Offline self-check in a private home: nothing is started, no model is needed.
    ENV["LAYA_CODEX_HOME"] = (testpath/"home").to_s
    ENV["LAYA_CODEX_NO_MODEL"] = "1"
    ENV["LAYA_CODEX_MOON_PORT"] = free_port.to_s
    (testpath/"repo").mkpath
    system "git", "-C", testpath/"repo", "init", "--quiet"
    # Exit status is 1 because the test repo has no hooks; the report must still parse, and it
    # must pick the bundled moon in libexec (found through the bin/ symlink, not another \`moon\`
    # on PATH) and a usable home.
    report = JSON.parse(shell_output("#{bin}/laya-codex doctor --json --repo #{testpath}/repo", 1))
    checks = report["checks"].to_h { |c| [c["name"], c] }
    assert_equal "pass", checks["moon"]["level"]
    assert_match "#{libexec.realpath}/moon", checks["moon"]["detail"]
    assert_equal "pass", checks["home"]["level"]
    assert_equal "fail", checks["hooks"]["level"]
  end
end
EOF

# Sanity: every checksum landed and no placeholder is left empty.
if grep -q 'sha256 ""' "$tmp/formula.rb"; then die "a checksum is missing"; fi
mkdir -p "$(dirname "$formula")"
cp "$tmp/formula.rb" "$formula"
printf 'update-formula: wrote %s (laya-codex %s)\n' "$formula" "$ver"
