#!/bin/sh
# Regenerate the Homebrew formula (packaging/homebrew/laya-codex.rb) for a published release:
# version, URLs and sha256 values come from the release's <asset>.sha256 files.
#
#   scripts/update-formula.sh 0.2.0                    # or v0.2.0
#   scripts/update-formula.sh 0.2.0 path/to/laya-codex.rb
#
# The CLI's name is detected from the release: if laya-codex-v<ver>-<target>.tar.gz exists the
# formula installs and tests `laya-codex` with LAYA_CODEX_* env vars (v0.2.0 on), otherwise
# `laya` with LAYA_* (v0.1.x). LAYA_FORMULA_BIN=laya|laya-codex skips the detection.
# The formula is written only after every checksum was fetched and validated, so a failed run
# leaves it untouched. LAYA_RELEASES_URL points at a mirror (or a file:// tree in tests).
set -eu

REPO="pilotspace/laya-codex"
RELEASES_URL="${LAYA_RELEASES_URL:-https://github.com/$REPO/releases}"
MAC=aarch64-apple-darwin
LINUX=x86_64-unknown-linux-gnu

die() { printf 'update-formula: error: %s\n' "$*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $0 <version> [formula]"
ver="${1#v}"
case "$ver" in
    [0-9]*.[0-9]*.[0-9]*) ;;
    *) die "version must look like 1.2.3 (got '$1')" ;;
esac
formula="${2:-$(cd "$(dirname "$0")/.." && pwd)/packaging/homebrew/laya-codex.rb}"
tag="v$ver"
base="$RELEASES_URL/download/$tag"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

# get_sum <asset>: its sha256 from <asset>.sha256; fails if missing or malformed.
get_sum() {
    curl --fail --silent --location --retry 3 --connect-timeout 15 --max-time 60 \
        --output "$tmp/one" "$base/$1.sha256" 2>/dev/null || return 1
    s="$(cut -d' ' -f1 <"$tmp/one")"
    printf '%s' "$s" | grep -Eq '^[0-9a-f]{64}$' || die "bad checksum in $1.sha256: '$s'"
    printf '%s' "$s"
}

bin="${LAYA_FORMULA_BIN:-}"
if [ -z "$bin" ]; then
    if get_sum "laya-codex-$tag-$MAC.tar.gz" >/dev/null; then bin=laya-codex; else bin=laya; fi
fi
case "$bin" in
    laya) env_prefix=LAYA ;;
    laya-codex) env_prefix=LAYA_CODEX ;;
    *) die "LAYA_FORMULA_BIN must be laya or laya-codex (got '$bin')" ;;
esac
printf 'update-formula: %s: binary %s, env %s_*\n' "$tag" "$bin" "$env_prefix"

for a in "$bin-$tag-$MAC" "moon-$tag-$MAC" "$bin-$tag-$LINUX" "moon-$tag-$LINUX"; do
    s="$(get_sum "$a.tar.gz")" || die "cannot fetch $a.tar.gz.sha256 (is $tag published?)"
    printf 'update-formula: %s.tar.gz %s\n' "$a" "$s"
    eval "sum_$(printf '%s' "$a" | tr -c 'a-zA-Z0-9\n' _)=\$s"
done
key() { printf 'sum_%s' "$(printf '%s' "$1" | tr -c 'a-zA-Z0-9\n' _)"; }
val() { eval "printf '%s' \"\$$(key "$1")\""; }

cat >"$tmp/formula.rb" <<EOF
# Homebrew formula for laya-codex. Published as Formula/laya-codex.rb in pilotspace/homebrew-tap:
#   brew install pilotspace/tap/laya-codex
# Generated by scripts/update-formula.sh $ver; regenerate rather than edit by hand.
class LayaCodex < Formula
  desc "Ranked code retrieval for Claude Code (tree-sitter + Moon + Laya re-ranker)"
  homepage "https://github.com/pilotspace/laya-codex"
  # laya-codex is Apache-2.0; the bundled Moon sidecar ships with a GPL-3.0 LICENSE text.
  license all_of: ["Apache-2.0", "GPL-3.0-only"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "$base/$bin-$tag-$MAC.tar.gz"
      sha256 "$(val "$bin-$tag-$MAC")"

      resource "moon" do
        url "$base/moon-$tag-$MAC.tar.gz"
        sha256 "$(val "moon-$tag-$MAC")"
      end
    end
  end

  on_linux do
    on_intel do
      url "$base/$bin-$tag-$LINUX.tar.gz"
      sha256 "$(val "$bin-$tag-$LINUX")"

      resource "moon" do
        url "$base/moon-$tag-$LINUX.tar.gz"
        sha256 "$(val "moon-$tag-$LINUX")"
      end
    end
  end

  # The CLI's name and env-var prefix for this release (renamed laya -> laya-codex in v0.2.0).
  def cli
    "$bin"
  end

  def env_prefix
    "$env_prefix"
  end

  def install
    # The CLI runs \`moon\` from beside its own binary first, so both live in libexec. Only the CLI
    # is exposed: homebrew-core's unrelated \`moon\` (moonrepo) owns bin/moon. The wrapper execs
    # the real binary, so the CLI's own path (and so the moon it picks) is libexec.
    libexec.install cli
    bin.write_exec_script libexec/cli
    pkgshare.install "THIRD-PARTY-LICENSES.txt"
    resource("moon").stage do
      libexec.install "moon"
      (pkgshare/"moon").install "LICENSE", "SOURCE"
    end
  end

  def caveats
    <<~EOS
      The laya-code re-ranker (~850 MB) is not part of this formula. Without it #{cli} ranks
      lexically. To download and verify it:
        curl -fsSL https://raw.githubusercontent.com/pilotspace/laya-codex/main/install.sh | sh -s -- --model-only

      Enable it in Claude Code, either everywhere with the plugin (inside Claude Code):
        /plugin marketplace add pilotspace/laya-codex
        /plugin install laya-codex@laya-codex
      or per repository (hooks then point at this version's Cellar path, so re-run it after
      \`brew upgrade laya-codex\`):
        #{cli} init --repo /path/to/repo
      Then check the setup with:
        #{cli} doctor --repo /path/to/repo
    EOS
  end

  test do
    require "json"

    assert_match "Usage: #{cli}", shell_output("#{bin}/#{cli} --help")
    assert_match "Usage: moon", shell_output("#{libexec}/moon --help")

    # Offline self-check in a private home: nothing is started, no model is needed.
    ENV["#{env_prefix}_HOME"] = (testpath/"home").to_s
    ENV["#{env_prefix}_NO_MODEL"] = "1"
    ENV["#{env_prefix}_MOON_PORT"] = free_port.to_s
    (testpath/"repo").mkpath
    system "git", "-C", testpath/"repo", "init", "--quiet"
    # Exit status is 1 because the test repo has no hooks; the report must still parse, and it
    # must pick the bundled moon beside the CLI (not another \`moon\` on PATH) and a usable home.
    report = JSON.parse(shell_output("#{bin}/#{cli} doctor --json --repo #{testpath}/repo", 1))
    checks = report["checks"].to_h { |c| [c["name"], c] }
    assert_equal "pass", checks["moon"]["level"]
    assert_match "#{libexec}/moon", checks["moon"]["detail"]
    assert_equal "pass", checks["home"]["level"]
    assert_equal "fail", checks["hooks"]["level"]
  end
end
EOF

# Sanity: every checksum landed and no placeholder is left empty.
if grep -q 'sha256 ""' "$tmp/formula.rb"; then die "a checksum is missing"; fi
mkdir -p "$(dirname "$formula")"
cp "$tmp/formula.rb" "$formula"
printf 'update-formula: wrote %s (%s %s)\n' "$formula" "$bin" "$ver"
