# Homebrew formula for laya-codex. Published as Formula/laya-codex.rb in pilotspace/homebrew-tap:
#   brew install pilotspace/tap/laya-codex
# Generated by scripts/update-formula.sh 0.1.2; regenerate rather than edit by hand.
class LayaCodex < Formula
  desc "Ranked code retrieval for Claude Code (tree-sitter + Moon + Laya re-ranker)"
  homepage "https://github.com/pilotspace/laya-codex"
  # laya-codex is Apache-2.0; the bundled Moon sidecar ships with a GPL-3.0 LICENSE text.
  license all_of: ["Apache-2.0", "GPL-3.0-only"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/pilotspace/laya-codex/releases/download/v0.1.2/laya-v0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "7a24a18cc1b637fb9c2d02340ed2e44cfed1730b919d69ea256e081cae0cf4c0"

      resource "moon" do
        url "https://github.com/pilotspace/laya-codex/releases/download/v0.1.2/moon-v0.1.2-aarch64-apple-darwin.tar.gz"
        sha256 "65d366a5bd9302fe2caf210a6db4365cdd681304393ba0307d7e5345dda0df1c"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pilotspace/laya-codex/releases/download/v0.1.2/laya-v0.1.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a527bd0295d036c4e1adeabd943d90ee65534123ffbc8edcf605cd8f3e849bba"

      resource "moon" do
        url "https://github.com/pilotspace/laya-codex/releases/download/v0.1.2/moon-v0.1.2-x86_64-unknown-linux-gnu.tar.gz"
        sha256 "678fead27bc502354178c4ca7f2367ab3ae6b22f532fccdce7a647aeac0da0de"
      end
    end
  end

  # The CLI's name and env-var prefix for this release (renamed laya -> laya-codex in v0.2.0).
  def cli
    "laya"
  end

  def env_prefix
    "LAYA"
  end

  def install
    # The CLI runs `moon` from beside its own binary first, so both live in libexec. Only the CLI
    # is exposed: homebrew-core's unrelated `moon` (moonrepo) owns bin/moon. The wrapper execs
    # the real binary, so the CLI's own path (and so the moon it picks) is libexec.
    libexec.install cli
    bin.write_exec_script libexec/cli
    pkgshare.install "THIRD-PARTY-LICENSES.txt"
    resource("moon").stage do
      libexec.install "moon"
      (pkgshare/"moon").install "LICENSE", "SOURCE"
    end
  end

  def caveats
    <<~EOS
      The laya-code re-ranker (~850 MB) is not part of this formula. Without it #{cli} ranks
      lexically. To download and verify it:
        curl -fsSL https://raw.githubusercontent.com/pilotspace/laya-codex/main/install.sh | sh -s -- --model-only

      Enable it in Claude Code, either everywhere with the plugin (inside Claude Code):
        /plugin marketplace add pilotspace/laya-codex
        /plugin install laya-codex@laya-codex
      or per repository (hooks then point at this version's Cellar path, so re-run it after
      `brew upgrade laya-codex`):
        #{cli} init --repo /path/to/repo
      Then check the setup with:
        #{cli} doctor --repo /path/to/repo
    EOS
  end

  test do
    require "json"

    assert_match "Usage: #{cli}", shell_output("#{bin}/#{cli} --help")
    assert_match "Usage: moon", shell_output("#{libexec}/moon --help")

    # Offline self-check in a private home: nothing is started, no model is needed.
    ENV["#{env_prefix}_HOME"] = (testpath/"home").to_s
    ENV["#{env_prefix}_NO_MODEL"] = "1"
    ENV["#{env_prefix}_MOON_PORT"] = free_port.to_s
    (testpath/"repo").mkpath
    system "git", "-C", testpath/"repo", "init", "--quiet"
    # Exit status is 1 because the test repo has no hooks; the report must still parse, and it
    # must pick the bundled moon beside the CLI (not another `moon` on PATH) and a usable home.
    report = JSON.parse(shell_output("#{bin}/#{cli} doctor --json --repo #{testpath}/repo", 1))
    checks = report["checks"].to_h { |c| [c["name"], c] }
    assert_equal "pass", checks["moon"]["level"]
    assert_match "#{libexec}/moon", checks["moon"]["detail"]
    assert_equal "pass", checks["home"]["level"]
    assert_equal "fail", checks["hooks"]["level"]
  end
end
