# Homebrew formula for laya-codex. Published as Formula/laya-codex.rb in pilotspace/homebrew-tap:
#   brew install pilotspace/tap/laya-codex
# Generated by scripts/update-formula.sh 0.2.0; regenerate rather than edit by hand.
class LayaCodex < Formula
  desc "Ranked code retrieval for Claude Code (tree-sitter + Moon + Laya re-ranker)"
  homepage "https://github.com/pilotspace/laya-codex"
  # laya-codex is Apache-2.0; the bundled Moon sidecar ships with a GPL-3.0 LICENSE text.
  license all_of: ["Apache-2.0", "GPL-3.0-only"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/pilotspace/laya-codex/releases/download/v0.2.0/laya-codex-v0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "8ff42b67dc0695328cde6132822fe217efbf1d0f8d7839d5dab555bd330115df"

      resource "moon" do
        url "https://github.com/pilotspace/laya-codex/releases/download/v0.2.0/moon-v0.2.0-aarch64-apple-darwin.tar.gz"
        sha256 "00b46d6edf9ef041d64da2b91d6c71c25ad973026092a7ced46a471f35ec263d"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pilotspace/laya-codex/releases/download/v0.2.0/laya-codex-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "cf49dd52ca32b53493595dd853729ce6d5b670cc98fe1cc23d734d063dbb0910"

      resource "moon" do
        url "https://github.com/pilotspace/laya-codex/releases/download/v0.2.0/moon-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
        sha256 "7e52dbb7f973c3c26c5cd2c707b9772c94d3470f35e23face852848a36a64ac2"
      end
    end
  end

  def install
    # laya-codex resolves its own symlink and runs the Moon in ../libexec, so the binary is linked
    # into bin as usual and `init` writes the bare `laya-codex` command (not a versioned Cellar
    # path). Moon stays in libexec: homebrew-core's unrelated `moon` (moonrepo) owns bin/moon.
    bin.install "laya-codex"
    pkgshare.install "THIRD-PARTY-LICENSES.txt"
    resource("moon").stage do
      libexec.install "moon"
      (pkgshare/"moon").install "LICENSE", "SOURCE"
    end
  end

  def caveats
    <<~EOS
      The laya-code re-ranker (~850 MB, a fine-tune of the Laya model) is not part of this
      formula. Without it laya-codex ranks lexically. To download and verify it:
        curl -fsSL https://raw.githubusercontent.com/pilotspace/laya-codex/main/install.sh | sh -s -- --model-only

      Enable it in Claude Code, either everywhere with the plugin (inside Claude Code):
        /plugin marketplace add pilotspace/laya-codex
        /plugin install laya-codex@laya-codex
      or per repository:
        laya-codex init --repo /path/to/repo
      Then check the setup with:
        laya-codex doctor --repo /path/to/repo

      Upgrading from 0.1.x: the CLI is now `laya-codex` (was `laya`) and its environment
      variables are LAYA_CODEX_* (were LAYA_*). Re-run `laya-codex init` in repositories set up
      with `laya init` and delete their old `laya hook` entries.
    EOS
  end

  test do
    require "json"

    assert_match "Usage: laya-codex", shell_output("#{bin}/laya-codex --help")
    assert_match "Usage: moon", shell_output("#{libexec}/moon --help")

    # Offline self-check in a private home: nothing is started, no model is needed.
    ENV["LAYA_CODEX_HOME"] = (testpath/"home").to_s
    ENV["LAYA_CODEX_NO_MODEL"] = "1"
    ENV["LAYA_CODEX_MOON_PORT"] = free_port.to_s
    (testpath/"repo").mkpath
    system "git", "-C", testpath/"repo", "init", "--quiet"
    # Exit status is 1 because the test repo has no hooks; the report must still parse, and it
    # must pick the bundled moon in libexec (found through the bin/ symlink, not another `moon`
    # on PATH) and a usable home.
    report = JSON.parse(shell_output("#{bin}/laya-codex doctor --json --repo #{testpath}/repo", 1))
    checks = report["checks"].to_h { |c| [c["name"], c] }
    assert_equal "pass", checks["moon"]["level"]
    assert_match "#{libexec.realpath}/moon", checks["moon"]["detail"]
    assert_equal "pass", checks["home"]["level"]
    assert_equal "fail", checks["hooks"]["level"]
  end
end
